/*

 INTRO.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : pressstarttiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define introWidth 20
#define introHeight 18
#define introBank 0

extern unsigned char intro[];

/* End of INTRO.H */
