/*

 LEVEL1_1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 50 x 18
   Tile set      : tiles_level1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level1_1Width 50
#define level1_1Height 18
#define level1_1Bank 0

extern unsigned char level1_1[];

/* End of LEVEL1_1.H */
